# Defaults tasks for role krb5-client

- name: Importing specific distro variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
  tags:
    - vars

- name: Ensuring krb5 needed packages are installed
  yum:
    name: "{{ krb5_pkgs }}"
    state: installed

- name: Distribute needed CA certs for pkinit_anchors (if defined)
  copy:
    src: "{{ pkistore }}/{{ item }}"
    dest: "/etc/pki/tls/certs/{{ item }}"
  with_items: "{{ krb5_pkinit_anchors_ca_list }}"

- name: Distribute krb5.conf config file
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644
